baseURL = "https://yenchunli.github.io"
languageCode = "en-us"
title = "yenchunli Website"
theme = "m10c"
themeDir = "../"
paginate = 8

[taxonomies]
  tag = "tags"

[author]
	name = "yenchunli"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
	# Blog description at the top of the homepage. Supports markdown.
	description = "Hello, I'm Yen-Chun Li. My dream is to create things people like."

  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/yenchunli"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 2

[[menu.main]]
	name = "Archives"
	identifier = "archives"
	url = "/archives/"
	weight = 3

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
