baseURL = "https://412988937.github.io"
languageCode = "en-us"
title = "412988937 Website"

[taxonomies]
  tag = "tags"

[author]
	name = "412988937"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "Hello, I'm Yen Chun Li. My dream is to create things people like."

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
    email = "nthucsbg@gmail.com"
    twitter = "#"
    linkedin = "#"

	# Writing
    medium = "#"

	# Creative & Visual

	# Programming
    github = "https://github.com/412988937"

    # Academic

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 2

[[menu.main]]
	name = "Archives"
	identifier = "archives"
	url = "/archives/"
	weight = 3

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
